config-version: 2
name: 'asana'
version: '1.0.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  asana:
    +schema: asana
    +materialized: table
    intermediate:
      +materialized: ephemeral
    staging:
      +schema: stg_asana
      +materialized: table
vars:
  asana:
    project_task: "{{ source('asana', 'project_task') }}"
    project: "{{ source('asana', 'project') }}"
    section: "{{ source('asana', 'section') }}"
    story: "{{ source('asana', 'story') }}"
    tag: "{{ source('asana', 'tag') }}"
    task_follower: "{{ source('asana', 'task_follower') }}"
    task_section: "{{ source('asana', 'task_section') }}"
    task_tag: "{{ source('asana', 'task_tag') }}"
    task: "{{ source('asana', 'task') }}"
    team: "{{ source('asana', 'team') }}"
    user: "{{ source('asana', 'user') }}"
    task_pass_through_columns: []
